# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

In [1]:
print("Hello World!")

Hello World!

In [9]:
import pandas

df=pandas.read_excel("British Airways Summer Schedule Dataset - Forage Data Science Task 1.xlsx")

df.head(3)

,FLIGHT_DATE,FLIGHT_TIME,TIME_OF_DAY,AIRLINE_CD,FLIGHT_NO,DEPARTURE_STATION_CD,ARRIVAL_STATION_CD,ARRIVAL_COUNTRY,ARRIVAL_REGION,HAUL,AIRCRAFT_TYPE,FIRST_CLASS_SEATS,BUSINESS_CLASS_SEATS,ECONOMY_SEATS,TIER1_ELIGIBLE_PAX,TIER2_ELIGIBLE_PAX,TIER3_ELIGIBLE_PAX
0,2025-09-02,14:19:00,Afternoon,BA,BA5211,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,10,38
1,2025-06-10,06:42:00,Morning,BA,BA7282,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,7,28
2,2025-10-27,15:33:00,Afternoon,BA,BA1896,LHR,FRA,Germany,Europe,SHORT,A320,0,17,163,0,11,40

In [11]:
df.shape

(10000, 17)

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   FLIGHT_DATE           10000 non-null  datetime64[us]
 1   FLIGHT_TIME           10000 non-null  object
 2   TIME_OF_DAY           10000 non-null  str
 3   AIRLINE_CD            10000 non-null  str
 4   FLIGHT_NO             10000 non-null  str
 5   DEPARTURE_STATION_CD  10000 non-null  str
 6   ARRIVAL_STATION_CD    10000 non-null  str
 7   ARRIVAL_COUNTRY       10000 non-null  str
 8   ARRIVAL_REGION        10000 non-null  str
 9   HAUL                  10000 non-null  str
 10  AIRCRAFT_TYPE         10000 non-null  str
 11  FIRST_CLASS_SEATS     10000 non-null  int64
 12  BUSINESS_CLASS_SEATS  10000 non-null  int64
 13  ECONOMY_SEATS         10000 non-null  int64
 14  TIER1_ELIGIBLE_PAX    10000 non-null  int64
 15  TIER2_ELIGIBLE_PAX    10000 non-null  int64
 16  TIER3_ELIGIBLE_PAX    10000 non-null  int64
dtypes: datetime64[us](1), int64(6), object(1), str(9)
memory usage: 1.3+ MB

In [15]:
df.columns

Index(['FLIGHT_DATE', 'FLIGHT_TIME', 'TIME_OF_DAY', 'AIRLINE_CD', 'FLIGHT_NO',
       'DEPARTURE_STATION_CD', 'ARRIVAL_STATION_CD', 'ARRIVAL_COUNTRY',
       'ARRIVAL_REGION', 'HAUL', 'AIRCRAFT_TYPE', 'FIRST_CLASS_SEATS',
       'BUSINESS_CLASS_SEATS', 'ECONOMY_SEATS', 'TIER1_ELIGIBLE_PAX',
       'TIER2_ELIGIBLE_PAX', 'TIER3_ELIGIBLE_PAX'],
      dtype='str')

In [16]:
df.describe()

,FLIGHT_DATE,FIRST_CLASS_SEATS,BUSINESS_CLASS_SEATS,ECONOMY_SEATS,TIER1_ELIGIBLE_PAX,TIER2_ELIGIBLE_PAX,TIER3_ELIGIBLE_PAX
count,10000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,2025-07-14 07:04:04.800000,1.547200,25.073800,198.385900,0.607700,7.951900,30.421400
min,2025-04-01 00:00:00,0.000000,0.000000,160.000000,0.000000,0.000000,0.000000
25%,2025-05-22 00:00:00,0.000000,8.000000,167.000000,0.000000,4.000000,20.000000
50%,2025-07-13 00:00:00,0.000000,17.000000,175.000000,0.000000,8.000000,30.000000
75%,2025-09-06 00:00:00,0.000000,35.000000,180.000000,1.000000,11.000000,41.000000
max,2025-10-30 00:00:00,14.000000,97.000000,358.000000,20.000000,29.000000,92.000000
std,NaN,3.625395,22.142348,53.653478,1.006232,5.130752,15.284233

In [17]:
df.shape

(10000, 17)

In [18]:
df.head()

,FLIGHT_DATE,FLIGHT_TIME,TIME_OF_DAY,AIRLINE_CD,FLIGHT_NO,DEPARTURE_STATION_CD,ARRIVAL_STATION_CD,ARRIVAL_COUNTRY,ARRIVAL_REGION,HAUL,AIRCRAFT_TYPE,FIRST_CLASS_SEATS,BUSINESS_CLASS_SEATS,ECONOMY_SEATS,TIER1_ELIGIBLE_PAX,TIER2_ELIGIBLE_PAX,TIER3_ELIGIBLE_PAX
0,2025-09-02,14:19:00,Afternoon,BA,BA5211,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,10,38
1,2025-06-10,06:42:00,Morning,BA,BA7282,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,7,28
2,2025-10-27,15:33:00,Afternoon,BA,BA1896,LHR,FRA,Germany,Europe,SHORT,A320,0,17,163,0,11,40
3,2025-06-15,18:29:00,Evening,BA,BA5497,LHR,IST,Turkey,Europe,SHORT,A320,0,8,172,0,16,54
4,2025-08-25,20:35:00,Evening,BA,BA1493,LHR,FRA,Germany,Europe,SHORT,A320,0,13,167,0,6,27

In [26]:
df["TIME_OF_DAY"].unique()

<StringArray>
['Afternoon', 'Morning', 'Evening', 'Lunchtime']
Length: 4, dtype: str

In [28]:
for column in df.columns:
    print(f"{column} {df[column].unique()}")
    print("-----------------------")
    # df[column].value_counts()

FLIGHT_DATE <DatetimeArray>
['2025-09-02 00:00:00', '2025-06-10 00:00:00', '2025-10-27 00:00:00',
 '2025-06-15 00:00:00', '2025-08-25 00:00:00', '2025-07-12 00:00:00',
 '2025-09-16 00:00:00', '2025-04-24 00:00:00', '2025-05-17 00:00:00',
 '2025-05-01 00:00:00',
 ...
 '2025-07-10 00:00:00', '2025-07-23 00:00:00', '2025-04-19 00:00:00',
 '2025-08-26 00:00:00', '2025-10-07 00:00:00', '2025-09-18 00:00:00',
 '2025-09-24 00:00:00', '2025-06-09 00:00:00', '2025-08-07 00:00:00',
 '2025-10-23 00:00:00']
Length: 210, dtype: datetime64[us]
-----------------------
FLIGHT_TIME [datetime.time(14, 19) datetime.time(6, 42) datetime.time(15, 33) ...
 datetime.time(17, 38) datetime.time(11, 52) datetime.time(11, 24)]
-----------------------
TIME_OF_DAY <StringArray>
['Afternoon', 'Morning', 'Evening', 'Lunchtime']
Length: 4, dtype: str
-----------------------
AIRLINE_CD <StringArray>
['BA']
Length: 1, dtype: str
-----------------------
FLIGHT_NO <StringArray>
['BA5211', 'BA7282', 'BA1896', 'BA5497', 'BA1493', 'BA4954', 'BA9840',
 'BA7116', 'BA4424', 'BA4878',
 ...
 'BA6948', 'BA1385', 'BA7380', 'BA7896', 'BA6196', 'BA9029', 'BA2627',
 'BA1631', 'BA9712', 'BA8374']
Length: 6037, dtype: str
-----------------------
DEPARTURE_STATION_CD <StringArray>
['LHR']
Length: 1, dtype: str
-----------------------
ARRIVAL_STATION_CD <StringArray>
['LAX', 'FRA', 'IST', 'VIE', 'AMS', 'ORD', 'MUC', 'HND', 'CDG', 'ZRH', 'JFK',
 'MAD', 'DXB', 'BCN', 'DFW']
Length: 15, dtype: str
-----------------------
ARRIVAL_COUNTRY <StringArray>
[        'USA',     'Germany',      'Turkey',     'Austria', 'Netherlands',
       'Japan',      'France', 'Switzerland',       'Spain',         'UAE']
Length: 10, dtype: str
-----------------------
ARRIVAL_REGION <StringArray>
['North America', 'Europe', 'Asia', 'Middle East']
Length: 4, dtype: str
-----------------------
HAUL <StringArray>
['LONG', 'SHORT']
Length: 2, dtype: str
-----------------------
AIRCRAFT_TYPE <StringArray>
['B777', 'A320', 'A350', 'B787', 'A380']
Length: 5, dtype: str
-----------------------
FIRST_CLASS_SEATS [ 8  0 14]
-----------------------
BUSINESS_CLASS_SEATS [49 17  8 13 20 56  4 10  2 48 12 18 42  5 15 97  3  9 11  1 32 31 16 14
  6  7 19 35  0]
-----------------------
ECONOMY_SEATS [178 163 172 167 160 275 176 170 200 168 162 166 175 165 358 177 171 224
 169 179 304 173 300 164 174 161 180]
-----------------------
TIER1_ELIGIBLE_PAX [ 0  1  2  4  3  5  6  8  7  9 20]
-----------------------
TIER2_ELIGIBLE_PAX [10  7 11 16  6 12  5  9  0  2  3  8  1  4 18 14 13 15 21 20 23 29 19 17
 25 22 24 26 27]
-----------------------
TIER3_ELIGIBLE_PAX [38 28 40 54 27 55 42 23 39 34  0  3 22 14 35 16  8 53 31 32 12 36 21 26
 59 30 43 11 10 33  7 19 47 24 20 46 45 17 25 13 51 29 18 37 60 69 48 52
 64 15  6  5 41 73 44  9 90 66  1 58 63 50 56 49  4 62 61 78 57  2 68 70
 71 65 80 72 79 67 76 77 92 75 81 74 85 83]
-----------------------